import { Tile } from "../types/types";
import { TILES } from "./tiles";

export const DICE: Tile[][] = [
    [TILES.A, TILES.A, TILES.E, TILES.E, TILES.G, TILES.N],
    [TILES.A, TILES.B, TILES.B, TILES.J, TILES.O, TILES.O],
    [TILES.A, TILES.C, TILES.H, TILES.O, TILES.P, TILES.S],
    [TILES.A, TILES.F, TILES.F, TILES.K, TILES.P, TILES.S],
    [TILES.A, TILES.O, TILES.O, TILES.T, TILES.T, TILES.W],
    [TILES.C, TILES.I, TILES.M, TILES.O, TILES.T, TILES.U],
    [TILES.D, TILES.E, TILES.I, TILES.L, TILES.R, TILES.X],
    [TILES.D, TILES.E, TILES.L, TILES.R, TILES.V, TILES.Y],
    [TILES.D, TILES.I, TILES.S, TILES.T, TILES.T, TILES.Y],
    [TILES.E, TILES.E, TILES.G, TILES.H, TILES.N, TILES.W],
    [TILES.E, TILES.E, TILES.I, TILES.N, TILES.S, TILES.U],
    [TILES.E, TILES.H, TILES.R, TILES.T, TILES.V, TILES.W],
    [TILES.E, TILES.I, TILES.O, TILES.S, TILES.S, TILES.T],
    [TILES.E, TILES.L, TILES.R, TILES.T, TILES.T, TILES.Y],
    [TILES.H, TILES.I, TILES.M, TILES.N, TILES.U, TILES.Q],
    [TILES.H, TILES.L, TILES.N, TILES.N, TILES.R, TILES.Z],
];