import { Tile } from "../types/types";
import { TILES } from "./tiles";

// export const DICE: Tile[][] = [
//     [TILES.A, TILES.A, TILES.E, TILES.E, TILES.G, TILES.N],
//     [TILES.A, TILES.B, TILES.B, TILES.J, TILES.O, TILES.O],
//     [TILES.A, TILES.C, TILES.H, TILES.O, TILES.P, TILES.S],
//     [TILES.A, TILES.F, TILES.F, TILES.K, TILES.P, TILES.S],
//     [TILES.A, TILES.O, TILES.O, TILES.T, TILES.T, TILES.W],
//     [TILES.C, TILES.I, TILES.M, TILES.O, TILES.T, TILES.U],
//     [TILES.D, TILES.E, TILES.I, TILES.L, TILES.R, TILES.X],
//     [TILES.D, TILES.E, TILES.L, TILES.R, TILES.V, TILES.Y],
//     [TILES.D, TILES.I, TILES.S, TILES.T, TILES.T, TILES.Y],
//     [TILES.E, TILES.E, TILES.G, TILES.H, TILES.N, TILES.W],
//     [TILES.E, TILES.E, TILES.I, TILES.N, TILES.S, TILES.U],
//     [TILES.E, TILES.H, TILES.R, TILES.T, TILES.V, TILES.W],
//     [TILES.E, TILES.I, TILES.O, TILES.S, TILES.S, TILES.T],
//     [TILES.E, TILES.L, TILES.R, TILES.T, TILES.T, TILES.Y],
//     [TILES.H, TILES.I, TILES.M, TILES.N, TILES.U, TILES.Q],
//     [TILES.H, TILES.L, TILES.N, TILES.N, TILES.R, TILES.Z],
// ];

// export const DICE: Tile[][] = [
//     [TILES.A, TILES.A, TILES.C, TILES.I, TILES.O, TILES.T],
//     [TILES.A, TILES.H, TILES.M, TILES.O, TILES.R, TILES.S],
//     [TILES.E, TILES.G, TILES.K, TILES.L, TILES.U, TILES.Y],
//     [TILES.A, TILES.B, TILES.I, TILES.L, TILES.T, TILES.Y],
//     [TILES.A, TILES.C, TILES.D, TILES.E, TILES.M, TILES.P],
//     [TILES.E, TILES.G, TILES.I, TILES.N, TILES.T, TILES.V],
//     [TILES.G, TILES.I, TILES.L, TILES.R, TILES.U, TILES.W],
//     [TILES.E, TILES.L, TILES.P, TILES.S, TILES.T, TILES.U],
//     [TILES.D, TILES.E, TILES.N, TILES.O, TILES.S, TILES.W],
//     [TILES.A, TILES.C, TILES.E, TILES.L, TILES.R, TILES.S],
//     [TILES.A, TILES.B, TILES.J, TILES.M, TILES.O, TILES.Q],
//     [TILES.E, TILES.E, TILES.F, TILES.H, TILES.I, TILES.Y],
//     [TILES.E, TILES.H, TILES.I, TILES.N, TILES.P, TILES.S],
//     [TILES.D, TILES.K, TILES.N, TILES.O, TILES.T, TILES.U],
//     [TILES.A, TILES.D, TILES.E, TILES.N, TILES.V, TILES.Z],
//     [TILES.B, TILES.I, TILES.F, TILES.O, TILES.R, TILES.X],
// ];

export const DICE: Tile[][] = [
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.N, TILES.J],
    [TILES.E, TILES.R, TILES.S, TILES.T, TILES.L, TILES.K],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.U, TILES.Q],
    [TILES.N, TILES.R, TILES.S, TILES.T, TILES.A, TILES.X],
    [TILES.E, TILES.L, TILES.I, TILES.O, TILES.N, TILES.Z],
    [TILES.A, TILES.E, TILES.R, TILES.S, TILES.T, TILES.F],
    [TILES.I, TILES.O, TILES.N, TILES.L, TILES.U, TILES.V],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.N, TILES.W],
    [TILES.R, TILES.S, TILES.T, TILES.L, TILES.U, TILES.Y],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.N, TILES.M],
    [TILES.E, TILES.R, TILES.S, TILES.T, TILES.L, TILES.P],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.U, TILES.C],
    [TILES.N, TILES.R, TILES.S, TILES.T, TILES.A, TILES.G],
    [TILES.E, TILES.L, TILES.I, TILES.O, TILES.N, TILES.H],
    [TILES.A, TILES.E, TILES.R, TILES.S, TILES.T, TILES.D],
    [TILES.I, TILES.O, TILES.N, TILES.L, TILES.U, TILES.B],
];